### Importación de datos

In [25]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

#1. Análisis de facturación

In [26]:
facturacion_t1 = tienda["Precio"].sum()
facturacion_t2 = tienda2["Precio"].sum()
facturacion_t3 = tienda3["Precio"].sum()
facturacion_t4 = tienda4["Precio"].sum()

print("Tienda 1:", facturacion_t1)
print("Tienda 2:", facturacion_t2)
print("Tienda 3:", facturacion_t3)
print("Tienda 4:", facturacion_t4)

facturacion = {
    "Tienda 1": facturacion_t1,
    "Tienda 2": facturacion_t2,
    "Tienda 3": facturacion_t3,
    "Tienda 4": facturacion_t4
}

tienda_mayor = max(facturacion, key=facturacion.get)
print("Tienda con mayor facturación:", tienda_mayor)
print("Monto:", f"{facturacion[tienda_mayor]:,.0f}")

Tienda 1: 1150880400.0
Tienda 2: 1116343500.0
Tienda 3: 1098019600.0
Tienda 4: 1038375700.0
Tienda con mayor facturación: Tienda 1
Monto: 1,150,880,400

# 2. Ventas por categoría

In [34]:
#TIENDA 1
cat1 = tienda.groupby("Categoría del Producto").size().sort_values(ascending=False)
print("Tienda 1 - Ventas por categoría (Top 5)")
display(cat1.head(5))

Tienda 1 - Ventas por categoría (Top 5)

Categoría del Producto
Muebles                 465
Electrónicos            448
Juguetes                324
Electrodomésticos       312
Deportes y diversión    284
dtype: int64

In [35]:
#TIENDA 2
cat2 = tienda2.groupby("Categoría del Producto").size().sort_values(ascending=False)
print("Tienda 2 - Ventas por categoría (Top 5)")
display(cat2.head(5))

Tienda 2 - Ventas por categoría (Top 5)

Categoría del Producto
Muebles                 442
Electrónicos            422
Juguetes                313
Electrodomésticos       305
Deportes y diversión    275
dtype: int64

In [36]:
# TIENDA 3
cat3 = tienda3.groupby("Categoría del Producto").size().sort_values(ascending=False)
print("Tienda 3 - Ventas por categoría (Top 5)")
display(cat3.head(5))

Tienda 3 - Ventas por categoría (Top 5)

Categoría del Producto
Muebles                 499
Electrónicos            451
Juguetes                315
Electrodomésticos       278
Deportes y diversión    277
dtype: int64

In [37]:
# TIENDA 4
cat4 = tienda4.groupby("Categoría del Producto").size().sort_values(ascending=False)
print("Tienda 4 - Ventas por categoría (Top 5)")
display(cat4.head(5))

Tienda 4 - Ventas por categoría (Top 5)

Categoría del Producto
Muebles                 480
Electrónicos            451
Juguetes                338
Deportes y diversión    277
Electrodomésticos       254
dtype: int64

In [38]:
print("Resumen: categoría más popular por tienda")
print("Tienda 1:", cat1.index[0], "-", int(cat1.iloc[0]))
print("Tienda 2:", cat2.index[0], "-", int(cat2.iloc[0]))
print("Tienda 3:", cat3.index[0], "-", int(cat3.iloc[0]))
print("Tienda 4:", cat4.index[0], "-", int(cat4.iloc[0]))

Resumen: categoría más popular por tienda
Tienda 1: Muebles - 465
Tienda 2: Muebles - 442
Tienda 3: Muebles - 499
Tienda 4: Muebles - 480

# 3. Calificación promedio de la tienda

In [41]:
#TIENDA 1,2,3 Y 4
prom_t1 = tienda["Calificación"].mean()
prom_t2 = tienda2["Calificación"].mean()
prom_t3 = tienda3["Calificación"].mean()
prom_t4 = tienda4["Calificación"].mean()

print("Tienda 1 - Calificación promedio:", round(prom_t1, 2))
print("Tienda 2 - Calificación promedio:", round(prom_t2, 2))
print("Tienda 3 - Calificación promedio:", round(prom_t3, 2))
print("Tienda 4 - Calificación promedio:", round(prom_t4, 2))

calif_prom = {
    "Tienda 1": prom_t1,
    "Tienda 2": prom_t2,
    "Tienda 3": prom_t3,
    "Tienda 4": prom_t4
}

mejor = max(calif_prom, key=calif_prom.get)
peor = min(calif_prom, key=calif_prom.get)

print("\nMejor satisfacción:", mejor, "-", round(calif_prom[mejor], 2))
print("Menor satisfacción:", peor, "-", round(calif_prom[peor], 2))

Tienda 1 - Calificación promedio: 3.98
Tienda 2 - Calificación promedio: 4.04
Tienda 3 - Calificación promedio: 4.05
Tienda 4 - Calificación promedio: 4.0

Mejor satisfacción: Tienda 3 - 4.05
Menor satisfacción: Tienda 1 - 3.98

# 4. Productos más y menos vendidos

In [43]:
#TIENDA 1
p1 = tienda["Producto"].value_counts()

print("Tienda 1 - Productos más vendidos (Top 10)")
display(p1.head(10))

print("Tienda 1 - Productos menos vendidos (Top 10)")
display(p1.sort_values().head(10))

Tienda 1 - Productos más vendidos (Top 10)

Producto
Microondas                 60
TV LED UHD 4K              60
Armario                    60
Secadora de ropa           58
Mesa de noche              56
Bloques de construcción    56
Balón de baloncesto        55
Bicicleta                  54
Vaso térmico               54
Refrigerador               54
Name: count, dtype: int64

Tienda 1 - Productos menos vendidos (Top 10)

Producto
Auriculares con micrófono      33
Celular ABXY                   33
Olla de presión                35
Pandereta                      36
Mochila                        39
Ciencia de datos con Python    39
Cuerda para saltar             40
Asistente virtual              40
Muñeca bebé                    40
Dinosaurio Rex                 40
Name: count, dtype: int64

In [45]:
#TIENDA 2
p2 = tienda2["Producto"].value_counts()

print("Tienda 2 - Productos más vendidos (Top 10)")
display(p2.head(10))

print("Tienda 2 - Productos menos vendidos (Top 10)")
display(p2.sort_values().head(10))

Tienda 2 - Productos más vendidos (Top 10)

Producto
Iniciando en programación    65
Microondas                   62
Batería                      61
Guitarra acústica            58
Pandereta                    58
Secadora de ropa             57
Iphone 15                    55
Bloques de construcción      54
Armario                      54
Set de ollas                 52
Name: count, dtype: int64

Tienda 2 - Productos menos vendidos (Top 10)

Producto
Juego de mesa        32
Mesa de comedor      34
Impresora            34
Sillón               35
Auriculares          37
Asistente virtual    38
Cubertería           39
Smart TV             40
Celular ABXY         41
Estufa               42
Name: count, dtype: int64

In [46]:
#TIENDA 3
p3 = tienda3["Producto"].value_counts()

print("Tienda 3 - Productos más vendidos (Top 10)")
display(p3.head(10))

print("Tienda 3 - Productos menos vendidos (Top 10)")
display(p3.sort_values().head(10))

Tienda 3 - Productos más vendidos (Top 10)

Producto
Kit de bancas                57
Mesa de comedor              56
Cama king                    56
Set de ollas                 55
Mesa de noche                55
Smart TV                     54
Estufa                       53
Cuerda para saltar           53
Modelado predictivo          53
Carrito de control remoto    52
Name: count, dtype: int64

Tienda 3 - Productos menos vendidos (Top 10)

Producto
Bloques de construcción      35
Microondas                   36
Set de vasos                 36
Mochila                      36
Vaso térmico                 38
Guitarra eléctrica           38
Cubertería                   39
Auriculares con micrófono    39
Asistente virtual            39
Muñeca bebé                  39
Name: count, dtype: int64

In [48]:
#TIENDA 4
p4 = tienda4["Producto"].value_counts()

print("Tienda 4 - Productos más vendidos (Top 10)")
display(p4.head(10))

print("Tienda 4 - Productos menos vendidos (Top 10)")
display(p4.sort_values().head(10))

Tienda 4 - Productos más vendidos (Top 10)

Producto
Cama box                     62
Cubertería                   59
Dashboards con Power BI      56
Cama king                    56
Carrito de control remoto    55
Mesa de comedor              55
Mesa de noche                55
Smart TV                     54
Bloques de construcción      54
Pandereta                    52
Name: count, dtype: int64

Tienda 4 - Productos menos vendidos (Top 10)

Producto
Guitarra eléctrica             33
Armario                        34
Guitarra acústica              37
Ciencia de datos con Python    38
Lavadora de ropa               38
Refrigerador                   38
Ajedrez de madera              39
Smartwatch                     39
Celular ABXY                   39
Secadora de ropa               40
Name: count, dtype: int64

In [49]:
#RESUMEN (MAS VENDIDOS Y MENOS VENDIDOS)
print("Resumen (más y menos vendido por tienda)\n")

print("Tienda 1:", p1.index[0], "-", int(p1.iloc[0]), "| Menos:", p1.sort_values().index[0], "-", int(p1.sort_values().iloc[0]))
print("Tienda 2:", p2.index[0], "-", int(p2.iloc[0]), "| Menos:", p2.sort_values().index[0], "-", int(p2.sort_values().iloc[0]))
print("Tienda 3:", p3.index[0], "-", int(p3.iloc[0]), "| Menos:", p3.sort_values().index[0], "-", int(p3.sort_values().iloc[0]))
print("Tienda 4:", p4.index[0], "-", int(p4.iloc[0]), "| Menos:", p4.sort_values().index[0], "-", int(p4.sort_values().iloc[0]))

Resumen (más y menos vendido por tienda)

Tienda 1: Microondas - 60 | Menos: Auriculares con micrófono - 33
Tienda 2: Iniciando en programación - 65 | Menos: Juego de mesa - 32
Tienda 3: Kit de bancas - 57 | Menos: Bloques de construcción - 35
Tienda 4: Cama box - 62 | Menos: Guitarra eléctrica - 33

# 5. Envío promedio por tienda